name: Sync MTG Prices

on:
  schedule:
    - cron: '0 5 * * 0' # todos los domingos a las 05:00 UTC
  workflow_dispatch: # para poder ejecutarlo a mano también

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            https://dieosbuuvdixzqgffiiz.functions.supabase.co/sync_mtg_prices
